name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # update caches if package lock changed
          # if failed to find key with caches then do a restore for older key
          key: ${{ runner.os }}-node-${{ hashFiles('**/*/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
          
        
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
      
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./strapi-be/
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/coffee-be:latest
          
#   deploy: 
#     needs: build
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2 
#       - name: Deploy in EC2
#         env:
#             SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#             SERVER_HOST : ${{ secrets.SERVER_HOST }}
#             DEPLOY_ENV: staging
#             APP_PORT: 1337
#         run: |
#           echo "$SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
#           scp -o StrictHostKeyChecking=no -i private_key ./strapi-be/docker-compose.yaml ubuntu@$SERVER_HOST:/home/ubuntu
#           ssh -o StrictHostKeyChecking=no -i private_key ubuntu@$SERVER_HOST "
#               docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} &&
#               docker pull david8087/coffee-be:latest &&
#               docker-compose down &&
#               docker-compose up -d"
            


    

          
          
