name: staging
on:
  pull_request:
    branches: [staging]
  push:
    branches: [staging]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # update caches if package lock changed
          # if failed to find key with caches then do a restore for older key
          key: ${{ runner.os }}-node-${{ hashFiles('**/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Use NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      
      - name: test
        run: |
          cat ./strapi-be/Dockerfile
          echo "hellow orld
        
        
          
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./strapi-be/Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/coffee-be:latest
               
        
          
          
#       - name: Create a Release
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         run: npx semantic-release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          
#       - name: Deploy to staging
#         if: github.event_name == 'push'
#         run: npx surge --project ./build --domain fragile-trip.surge.sh
#         env:
#           SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
#           SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          
          
          
