name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
              
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
      
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ./strapi-be/
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/coffee-be:latest
          
  deploy: 
#     needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SERVER_HOST : ${{ secrets.SERVER_HOST }}
            DEPLOY_ENV: staging
            APP_PORT: 1337
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 400 private_key
          "API_ENDPOINT=${{ env.APP_PORT }}"
          echo ${{env.APP_PORT}}

        
            


    

          
          
