version: "3.3"
services:
  strapi:
    build: .
    image: david8087/na-strapi-app:latest
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      JWT_SECRET: ${JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      SEND_TO: ${SEND_TO}
      SEND_FROM: ${SEND_FROM}
    ports:
      - ${APP_PORT}:1337
    networks:
      - na-strapi-app

networks:
  na-strapi-app:
    external:
      name: na-strapi-app
