version: "3.3"
services:
  strapi:
    build: .
    image: david8087/coffee-be:latest
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: ${NODE_ENV}
    # volumes:
    #   - ./config:/opt/app/config
    #   - ./src:/opt/app/src
    #   - ./package.json:/opt/package.json
    #   - ./yarn.lock:/opt/yarn.lock # Replace with package-lock.json if using npm
    #   - ./Dockerfile:/opt/Dockerfile
    ports:
      - ${APP_PORT}:1337
    # networks:
    #   - strapi_service

# networks:
#   strapi_service:
#     external:
#       name: strapi_service
